
on:
  push:
    branches:
      - main # Or your default branch, e.g., master

jobs:
  build-android:
    runs-on: ubuntu-latest # Use a Linux environment for the build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # You can adjust this to match your Node.js version if needed

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Or 'zulu', 'adopt', etc.
          java-version: '21'    # Capacitor often requires JDK 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        # This action will install the necessary Android SDK components

      - name: Install npm dependencies
        run: npm install

      - name: Build Vite web app
        run: npm run build

      - name: Sync web assets to Android
        run: npx cap sync android

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew
        working-directory: ./android # Ensure this is where gradlew is

      - name: Build Android Debug APK
        run: ./gradlew assembleDebug # Or assembleRelease if you set up signing
        working-directory: ./android

      - name: Create Release Tag
        id: create_tag
        run: echo "TAG_NAME=v$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          body: |
            Automated release of Android app.
          draft: false
          prerelease: false

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./android/app/build/outputs/apk/debug/app-debug.apk # Path to your debug APK
          asset_name: app-debug.apk
          asset_content_type: application/vnd.android.package-archive
